version: '3.8'
services:
  subscriptions:
    image: subscriptions-service
    ports:
    - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/subscription
      SPRING_DATASOURCE_USERNAME: subscription
      SPRING_DATASOURCE_PASSWORD: s3cr3t
    links:
      - database:database
  database:
    image: mysql:8.0
    ports:
    - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: subscription
      MYSQL_USER: subscription
      MYSQL_PASSWORD: s3cr3t
