name: branch
on:
  push:
    branches:
      - "*"
      - "!master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up java 15
        uses: actions/setup-java@v3
        with:
          java-version: 15
          distribution: 'adopt'
          check-latest: false
      - name: build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file pom.xml
