name: master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: set up java 15
        uses: actions/setup-java@v3
        with:
          java-version: 15
          distribution: 'adopt'
          check-latest: false
      - name: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file pom.xml
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: set up java 15
        uses: actions/setup-java@v3
        with:
          java-version: 15
          distribution: 'adopt'
          check-latest: false
      - name: build
        run: >
          mvn -B compile jib:build
          -Djib.to.image=docker.io/dimasmith/subscriptions-service
          -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }}
          -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }}
          --file pom.xml
