name: master
on:
  push:
    branches:
      # todo: remove before merging
      - "*"
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up java 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: build
        run: mvn -B verify --file pom.xml
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up java 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: build
        run: >
          mvn -B verify jib:build
          -Djib.to.image=docker.io/dimasmith/subscriptions-service
          -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }}
          -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }}
          --file pom.xml
